.TH SYL 1
.SH SYL
syl \- convert from hexadecimal to syllables

.SH SYNOPSIS
syl [-s]

.SH DESCRIPTION
syl reads either pairs of hexadecimal numbers (default) or syllables
(-s) from stdin and converts them into each other. The syllables are
urbit syllables- pairs of them are separated by dashes ('-'), groups of
four are separated by double-dashes ('--'). If the number of characters
in a hexadecimal input line is odd, the last character is ignored.
Chars in the hexadecimal input have to be lowercase.

.SH EXAMPLE
.TP
.B $ echo ffff | syl
.TP
.B fapfes
.TP
convert from hexadecimal to urbit syllables.
.TP
.B $ echo digpet-novdex | syl -s
.TP
.B c1454639
.TP
convert syllables to hexadecimal.

.SH STATUS
0 on success and 1 when it prints the help message.

.SH BUGS
I am inexperienced with myrddin, so there may be
more elegant solutions to what I did.
.TP
It does not work yet.

.SH AUTHOR
pranomostro (pranomestro@gmail.com)
