.TH SYL 1
.SH SYL
syl \- convert from hexadecimal to syllables

.SH SYNOPSIS
syl [-s]

.SH DESCRIPTION
syl reads hexadecimal input (pairs of [0-9a-f]) and converts it to
urbit syllables.

.SH OPTIONS
.TP
.BI \-s
convert urbit syllables to hexadecimal, the default is the other way around.

.SH EXAMPLES
.P
.B $ echo ffff | syl
.br
.B fapfes
.TP
convert from hexadecimal to urbit syllables.
.P
.B $ echo digpet-novdex | syl -s
.br
.B c1454639
.TP
convert syllables to hexadecimal.
.TP
.B $ md5sum /bin/ls | awk '{ print($1) }' | syl
.TP
Convert the md5sum of /bin/ls to an urbit syllable string.

.SH STATUS
0 on success and 1 when it prints the usage.

.SH BUGS
I am inexperienced with myrddin, so there may be
more elegant solutions to what I did.

.SH "SEE ALSO"
.IR urbit(1).
I hope 1 is the right section, I don't want Mencious
Moldbug screaming at me...

.SH AUTHOR
pranomostro (pranomestro@gmail.com)
