.Dd May 11, 2017
.Dt TEMPLATE 1
.Os

.Sh NAME
.Nm syl
.Nd convert from hexadecimal to syllables and vice versa

.Sh SYNOPSIS
.Nm
.Op Fl s

.Sh DESCRIPTION
.Nm
reads hexadecimal input (pairs of [0-9a-f]) and converts it to urbit
syllables, or reads urbit syllables and converts them back. It does so
linewise.

.Sh OPTIONS
.Bl -tag -width Ds
.It Fl s
Convert syllables to hexadecimal input, the default is the other
way around.

.Sh EXAMPLES
Convert from hexadecimal to syllables:
.Pp
.Dl $ echo ffff | syl
.Dl fapfes
.Pp
Convert syllables to hexadecimal:
.Pp
.Dl $ echo digpet-novdex | syl -s
.Dl c1454639
.Pp
Convert an md5sum to a syllable string:
.Pp
.Dl $ md5sum /bin/ls | awk '{ print($1) }' | syl
.Dl witsul-posten-bollen-dacdus--posdeg-rolluc-fonwyx-nopsup

.Sh EXIT STATUS
.Ex -std

.Sh SEE ALSO
.Xr awk ,
.Xr echo 1 ,
.Xr md5sum ,
.Xr urbit 1 .

.Sh AUTHORS
.An pranomostro Aq Mt pranomostro@posteo.de
